#!/usr/bin/env node
// Execute a generated Figma script, then walk the rendered subtree by eid
// and write a rendered-ref JSON payload for `dd verify --rendered-ref`.
//
// Usage: node walk_ref.js <script.js> <output.json> [port=9228] [--keep-existing] [--grid-pos=row,col]
//
// --keep-existing: do NOT clear the Generated Test page before rendering.
//   Default behavior is to clear (one render at a time, preserves single-
//   screen probe semantics). Pass --keep-existing for sweep-mode runs
//   where you want all rendered screens to persist on the page so the
//   user can review them visually. Walk anchoring still works because
//   the eid_map walk starts from M['screen-1'] (the just-rendered root),
//   which the user code populates explicitly — not from `__page.children[0]`.
//
// --grid-pos=row,col: with --keep-existing, place the rendered root at
//   (col * GRID_DX, row * GRID_DY) instead of overlapping at 0,0.
//   Caller passes the per-screen grid index. Cell size is fixed (1700 x
//   1300) — generous enough to hold any iPhone/iPad/desktop screen with
//   margin. The grid is purely visual (eid_map walk and verifier are
//   unaffected by node x/y on the page).
//
// The output has shape:
//   {
//     __ok: true,
//     errors: [...],
//     rendered_root: "<figma-node-id>",
//     rendered_root_width, rendered_root_height,
//     eid_map: {
//       "<eid>": {
//         type: "<FIGMA_TYPE>",
//         name, width, height,
//         x, y,                              // post-rotation AABB TL, relative to root TL
//         rotation,                          // radians (0 for non-rotated)
//         characters, textAutoResize,        // TEXT only
//         fillGeometryCount, strokeGeometryCount,  // VECTOR / BOOLEAN_OPERATION
//       }
//     }
//   }
//
// x / y / rotation were added 2026-04-21 to support SoM-based
// component-coverage fidelity scoring (docs/research/scorer-calibration
// -and-som-fidelity.md). `dd/classify_vision_som.py`'s annotations
// format expects: {id, x, y, w, h, rotation} where x/y are post-rotation
// AABB TL relative to the screenshot's origin (which is the rendered
// root's TL for the screenshot we export). rotation is radians.
//
// Additive change only — existing consumers reading width/height/fills
// are unaffected; the new fields are present but ignored by them.

// Resolve `ws` via Node module resolution (see package.json).
const WebSocket = require('ws');
const fs = require('fs');
const path = require('path');

// Sprint 2 C7 — load the registry-derived walker manifest at script-start
// time so we can inject it into the wrapped script that runs inside the
// Figma plugin sandbox. Per docs/plan-sprint-2-station-parity.md §5
// (registry authority), the manifest is generated by dd/walker_manifest.py
// from dd/property_registry.py PROPERTIES; the on-disk artifact at
// render_test/walker_manifest.generated.json is the only thing the JS
// walker is allowed to read (no JS-mirroring registry).
//
// Plan §10 R1 (self-boot fallback): if the manifest read or parse fails,
// the walker MUST still work — emit a warning to stderr and continue with
// __WALKER_MANIFEST = null. C7 makes the manifest observable; C8 will
// make capture decisions read it. Until then there is no behavior change
// from a missing manifest.
//
// Path resolution uses __dirname (not cwd) so the walker works regardless
// of the working directory the Node process was launched from. sweep.py
// and the test suite both invoke walk_ref.js with arbitrary cwd.
let __WALKER_MANIFEST = null;
const __WALKER_MANIFEST_VERSION = '1.0';
try {
  const manifestPath = path.join(__dirname, 'walker_manifest.generated.json');
  __WALKER_MANIFEST = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
} catch (err) {
  console.error(
    '[walker] manifest read failed (self-boot fallback per plan §10 R1): '
    + err.message
  );
  __WALKER_MANIFEST = null;
}

async function run() {
  // Parse args. Positional: scriptPath, outPath, port. Flags:
  //   --keep-existing
  //   --grid-pos=ROW,COL  (with --keep-existing, place root at grid cell)
  const positional = [];
  let keepExisting = false;
  let gridRow = null, gridCol = null;
  for (const a of process.argv.slice(2)) {
    if (a === '--keep-existing') keepExisting = true;
    else if (a.startsWith('--grid-pos=')) {
      const v = a.slice('--grid-pos='.length);
      const m = v.match(/^(\d+),(\d+)$/);
      if (m) { gridRow = parseInt(m[1], 10); gridCol = parseInt(m[2], 10); }
    } else positional.push(a);
  }
  const scriptPath = positional[0];
  const outPath = positional[1];
  const port = parseInt(positional[2] || '9228', 10);
  if (!scriptPath || !outPath) {
    console.error('Usage: node walk_ref.js <script.js> <output.json> [port=9228] [--keep-existing] [--grid-pos=row,col]');
    process.exit(1);
  }

  const userCode = fs.readFileSync(scriptPath, 'utf8');
  // Strip the trailing `return M;` — we'll insert our own return that
  // wraps M in a structured payload with the walk result.
  const body = userCode.replace(/return M;\s*$/, '');

  // F12d: when --keep-existing is set, don't clear the page. Sweep mode
  // wants every rendered screen to persist for visual review. The walk
  // anchors on M['screen-1'] (populated by user code) so existing
  // children don't interfere with the eid_map walk.
  const clearPageStmt = keepExisting
    ? '// (--keep-existing: not clearing page; existing children preserved)'
    : 'for (const c of [...__page.children]) c.remove();';

  // F12d: optional post-render grid placement. Cell size is generous
  // enough to hold any common screen size (1440 desktop + iPad 1024 +
  // iPhone 430 all fit) with a 200px gutter for visual clarity.
  const GRID_DX = 1700;
  const GRID_DY = 1300;
  const gridPlacementStmt = (keepExisting && gridRow !== null && gridCol !== null)
    ? `// F12d grid placement: tile rendered root at (${gridRow}, ${gridCol})
const __gridRoot = M['screen-1'] ? await figma.getNodeByIdAsync(M['screen-1']) : null;
if (__gridRoot && typeof __gridRoot.x === 'number') {
  __gridRoot.x = ${gridCol * GRID_DX};
  __gridRoot.y = ${gridRow * GRID_DY};
}`
    : '// (no grid placement)';

  const wrapped = `
// Sprint 2 C7 — inject the registry-derived walker manifest into the
// plugin sandbox. The manifest is read on the Node side from
// render_test/walker_manifest.generated.json and serialized inline here
// so it is observable to capture handlers. C7 only injects + smoke-logs;
// C8 makes capture decisions read __WALKER_MANIFEST.properties (below).
const __WALKER_MANIFEST = ${JSON.stringify(__WALKER_MANIFEST)};
const __WALKER_MANIFEST_VERSION = ${JSON.stringify(__WALKER_MANIFEST_VERSION)};
if (__WALKER_MANIFEST && __WALKER_MANIFEST.properties) {
  console.log('[walker] manifest loaded: ' + Object.keys(__WALKER_MANIFEST.properties).length + ' properties');
} else {
  console.log('[walker] manifest not loaded (self-boot fallback)');
}

// Sprint 2 C8 — precompute the set of property names whose capture
// shape graduates from raw to {value, source} envelope. Per
// docs/plan-sprint-2-station-parity.md §6 (walker capture semantics)
// the manifest's per-property "envelope" field is the registry's
// instruction to the walker; "value_source" means the walker emits
// {value: <captured>, source: 'set'} instead of the bare value, so
// downstream consumers can distinguish a real assignment from a
// computed default / inherited value. Sprint 2 only emits the 'set'
// tag; broader source-tag vocabulary is reserved for future families.
//
// Self-boot fallback per plan §10 R1: if __WALKER_MANIFEST is null
// or missing the .properties field, fall back to a hardcoded Set of
// the 3 names this commit graduates so C8 still works under fallback.
const __VALUE_SOURCE_PROPS = (function () {
  const s = new Set();
  if (__WALKER_MANIFEST && __WALKER_MANIFEST.properties) {
    for (const name of Object.keys(__WALKER_MANIFEST.properties)) {
      if (__WALKER_MANIFEST.properties[name].envelope === 'value_source') {
        s.add(name);
      }
    }
    return s;
  }
  // Fallback: hardcode the 3 graduations from C8 so absence-of-manifest
  // doesn't silently regress to raw-only capture.
  s.add('characters');
  s.add('layoutSizingHorizontal');
  s.add('layoutSizingVertical');
  return s;
})();

function __walkerMaybeEnvelope(name, value, source) {
  return __VALUE_SOURCE_PROPS.has(name) ? { value: value, source: source } : value;
}

// Safeguard: resolve __page by NAME (never trust figma.currentPage —
// figma.getNodeByIdAsync side-effects it). Hard-assert identity before
// any destructive operation. If this ever trips, the file state is
// unexpected — refuse to run rather than risk clearing a source page.
const __OUTPUT_PAGE = 'Generated Test';
await figma.loadAllPagesAsync();
let __page = figma.root.children.find(p => p.name === __OUTPUT_PAGE);
if (!__page) { __page = figma.createPage(); __page.name = __OUTPUT_PAGE; }
await figma.setCurrentPageAsync(__page);
if (__page.name !== __OUTPUT_PAGE) {
  throw new Error('refusing to clear: resolved page is not ' + __OUTPUT_PAGE);
}
${clearPageStmt}

// P3d (Phase E N2 fix) — page-orphan signal.
// Snapshot top-level children BEFORE running user code. Any new
// top-level child after render that isn't the rendered root is an
// "escaped render artifact" — a node that the renderer created but
// failed to place inside the IR tree (typically appendChild rejected
// it, the F-series guards swallowed the throw, and the node landed
// on the page root instead of inside the screen frame). Pre-P3d the
// verifier had no signal for this class because the eid_map walk
// only descended from rootNode and never inspected siblings.
//
// Codex's design review (2026-04-25): use "rooted-tree" as the
// invariant — expected output = descendants of rootNode. M membership
// classifies the artifact (was-it-supposed-to-be-an-IR-node?) but
// does NOT excuse it (a new top-level page child outside rootNode is
// always an orphan). Emit ONE summary entry per artifact, not one
// per descendant — keeps verifier output proportional.
const __pre_ids = new Set(__page.children.map(c => c.id));

${body}

${gridPlacementStmt}

// Invert M so we can walk the rendered subtree keyed by eid.
const idToEid = {};
for (const k of Object.keys(M)) {
  if (k === '__errors' || k === '__canary' || k === '__perf') continue;
  idToEid[M[k]] = k;
}

// Find the rendered root — first screen-eid in M, falling back to the
// first top-level child on the page.
const rootId = M['screen-1'] || (__page.children[0] && __page.children[0].id);
const rootNode = rootId ? await figma.getNodeByIdAsync(rootId) : null;

// P3d: enumerate post-render top-level children, classify each new
// one. The rendered root itself is expected (it WAS the new top-level
// child the renderer created and populated). Anything else is escaped.
if (!M['__errors']) M['__errors'] = [];
for (const child of __page.children) {
  if (__pre_ids.has(child.id)) continue;        // existed before render
  if (rootNode && child.id === rootNode.id) continue;  // the rendered root
  // Walk the artifact subtree once to summarize it: count children,
  // sample any M-membership eids (so the verifier can credit-assign
  // an escaped artifact back to the IR position whose appendChild
  // failed). Bounded sample so a large orphan tree doesn't blow up
  // the error payload.
  let __child_count = 0;
  let __contains_m_id = false;
  const __m_eid_sample = [];
  const __MAX_SAMPLE = 5;
  try {
    const __stk = [child];
    while (__stk.length) {
      const __n = __stk.pop();
      __child_count += 1;
      const __eid = idToEid[__n.id];
      if (__eid) {
        __contains_m_id = true;
        if (__m_eid_sample.length < __MAX_SAMPLE) __m_eid_sample.push(__eid);
      }
      if ('children' in __n) for (const __c of __n.children) __stk.push(__c);
    }
  } catch (_) {}
  M['__errors'].push({
    kind: 'phase2_orphan',
    node_id: child.id,
    name: child.name || '',
    type: child.type,
    child_count: __child_count,
    contains_m_id: __contains_m_id,
    m_eid_sample: __m_eid_sample,
  });
}

// Capture the root's absolute bounding box so per-node x/y can be
// emitted relative to it. exportAsync renders a PNG whose origin is
// the root's TL, so screenshot-relative coords == root-relative coords.
const rootAbs = rootNode && rootNode.absoluteBoundingBox
  ? rootNode.absoluteBoundingBox
  : null;

const eid_map = {};
if (rootNode) {
  const stack = [rootNode];
  while (stack.length) {
    const n = stack.pop();
    const eid = idToEid[n.id];
    if (eid) {
      const entry = {
        type: n.type,
        name: n.name,
        width: n.width,
        height: n.height,
      };
      // Post-rotation AABB TL relative to the root's TL. When either
      // absoluteBoundingBox is null (unusual — detached node), we fall
      // back to 0,0 so downstream consumers don't see NaN, but flag via
      // the diagnostic channel for auditability.
      try {
        const ab = n.absoluteBoundingBox;
        if (ab && rootAbs) {
          entry.x = ab.x - rootAbs.x;
          entry.y = ab.y - rootAbs.y;
        } else {
          entry.x = 0;
          entry.y = 0;
        }
      } catch (_) {
        entry.x = 0;
        entry.y = 0;
      }
      // Figma's node.rotation is in degrees; classify_vision_som
      // render_som_overlay wants radians. Convert here so downstream
      // consumers do not need to know the Figma-specific unit.
      try {
        const deg = (typeof n.rotation === 'number') ? n.rotation : 0;
        entry.rotation = deg * Math.PI / 180;
      } catch (_) {
        entry.rotation = 0;
      }
      // P1b (forensic-audit-2 findings 8-12): capture the visual props
      // the renderer emits via the registry-driven path so the verifier
      // can compare them against IR. Pre-fix the walker only captured
      // rotation; opacity/blendMode/isMask/cornerRadius drift was
      // invisible.
      try {
        if (typeof n.opacity === 'number') entry.opacity = n.opacity;
      } catch (_) {}
      try {
        if (typeof n.blendMode === 'string') entry.blendMode = n.blendMode;
      } catch (_) {}
      try {
        if (typeof n.isMask === 'boolean') entry.isMask = n.isMask;
      } catch (_) {}
      // cornerRadius is uniform on rectangles/frames, mixed (per-corner)
      // on those that use the figma.Mixed sentinel. Per-corner values
      // surface as topLeftRadius etc; we capture both shapes so the
      // verifier can compare uniform-vs-uniform or mixed-vs-mixed.
      try {
        if (typeof n.cornerRadius === 'number') {
          entry.cornerRadius = n.cornerRadius;
        } else if (n.cornerRadius && typeof n.cornerRadius === 'symbol') {
          // figma.Mixed — the node has per-corner radii.
          entry.cornerRadiusMixed = true;
          if (typeof n.topLeftRadius === 'number') entry.topLeftRadius = n.topLeftRadius;
          if (typeof n.topRightRadius === 'number') entry.topRightRadius = n.topRightRadius;
          if (typeof n.bottomRightRadius === 'number') entry.bottomRightRadius = n.bottomRightRadius;
          if (typeof n.bottomLeftRadius === 'number') entry.bottomLeftRadius = n.bottomLeftRadius;
        }
      } catch (_) {}
      // A5 (forensic-audit-2 Pattern G): capture stroke-geometry +
      // clipsContent for verifier comparison. Pre-A5 these were
      // emitted by the renderer (registry _UNIFORM templates) but
      // never compared by the verifier — silent drift.
      try {
        if (typeof n.strokeWeight === 'number') entry.strokeWeight = n.strokeWeight;
      } catch (_) {}
      try {
        if (typeof n.strokeAlign === 'string') entry.strokeAlign = n.strokeAlign;
      } catch (_) {}
      try {
        if (Array.isArray(n.dashPattern)) entry.dashPattern = n.dashPattern.slice();
      } catch (_) {}
      try {
        if (typeof n.clipsContent === 'boolean') entry.clipsContent = n.clipsContent;
      } catch (_) {}
      // Sprint 2 C8 — layoutSizingHorizontal/Vertical are graduated
      // to {value, source} envelopes via __walkerMaybeEnvelope. The
      // typeof === 'string' guard covers nodes that don't expose the
      // sizing properties (e.g. GROUP) and the figma.Mixed sentinel;
      // absence of the entry implies the property was not present on
      // the node, rather than emitting a placeholder envelope. C10
      // will register comparators on the verifier side; for now the
      // captures land in the rendered map and any future read sites
      // tolerate either shape via _rendered_value.
      try {
        if (typeof n.layoutSizingHorizontal === 'string') {
          entry.layoutSizingHorizontal = __walkerMaybeEnvelope('layoutSizingHorizontal', n.layoutSizingHorizontal, 'set');
        }
      } catch (_) {}
      try {
        if (typeof n.layoutSizingVertical === 'string') {
          entry.layoutSizingVertical = __walkerMaybeEnvelope('layoutSizingVertical', n.layoutSizingVertical, 'set');
        }
      } catch (_) {}
      if (n.type === 'TEXT') {
        // Sprint 2 C8 — characters graduates to {value, source}
        // envelope. textAutoResize stays raw (not in the C8
        // graduation list).
        entry.characters = __walkerMaybeEnvelope('characters', n.characters || '', 'set');
        entry.textAutoResize = n.textAutoResize;
      }
      if (n.type === 'VECTOR' || n.type === 'BOOLEAN_OPERATION') {
        // fillGeometry / strokeGeometry are arrays of path objects. A
        // VECTOR with no paths renders as an invisible rectangle (the
        // fill/stroke still exists but has nothing to draw against).
        // Attribute those nodes so the verifier can flag them with
        // KIND_MISSING_ASSET.
        try {
          entry.fillGeometryCount = (n.fillGeometry || []).length;
        } catch (_) { entry.fillGeometryCount = 0; }
        try {
          entry.strokeGeometryCount = (n.strokeGeometry || []).length;
        } catch (_) { entry.strokeGeometryCount = 0; }
      }
      // Capture SOLID fills/strokes for KIND_FILL_MISMATCH /
      // KIND_STROKE_MISMATCH verification. Normalized to the same shape
      // as the IR: [{type, color}]. Only SOLID for now.
      const toHex = (v) => Math.round(Math.min(1, Math.max(0, v)) * 255)
        .toString(16).padStart(2, '0').toUpperCase();
      const normalizeSolids = (paints) => {
        if (!Array.isArray(paints)) return null;
        const out = [];
        for (const p of paints) {
          if (p.visible === false) continue;
          if (p.type === 'SOLID' && p.color) {
            out.push({ type: 'solid', color: '#' + toHex(p.color.r) + toHex(p.color.g) + toHex(p.color.b) });
          }
        }
        return out.length > 0 ? out : null;
      };
      try { const f = normalizeSolids(n.fills); if (f) entry.fills = f; } catch (_) {}
      try { const s = normalizeSolids(n.strokes); if (s) entry.strokes = s; } catch (_) {}
      // Effect count for KIND_EFFECT_MISSING — just the count, not full data.
      try {
        const fx = n.effects;
        if (Array.isArray(fx)) {
          entry.effectCount = fx.filter(e => e.visible !== false).length;
        }
      } catch (_) {}
      eid_map[eid] = entry;
    }
    if ('children' in n) for (const c of n.children) stack.push(c);
  }
}

return {
  __ok: true,
  errors: M['__errors'] || [],
  perf: M['__perf'] || null,
  rendered_root: rootId,
  rendered_root_width: rootNode ? rootNode.width : 0,
  rendered_root_height: rootNode ? rootNode.height : 0,
  eid_map,
};
`;

  return new Promise((resolve, reject) => {
    const ws = new WebSocket('ws://localhost:' + port);
    const id = 'walk_' + Date.now();
    // Timeout is configurable via BRIDGE_TIMEOUT_MS env var (applies
    // to both the PROXY_EXECUTE server-side timeout sent to the
    // Figma plugin AND the WebSocket client-side watchdog). Default
    // raised 170000 → 300000 on 2026-04-22 after confirming (via
    // Figma plugin-sandbox research) that Figma itself enforces NO
    // hard timeout on plugin scripts — the old 170s figure was the
    // Desktop Bridge wrapper's limit, not Figma's. Under heavy plugin
    // load (iPad-sized screens + slot-inlined children post Option 2
    // type/role + slot-flatten fix) renders legitimately need
    // 200-300s; raising the default is safe because the bridge still
    // enforces per-screen retry on true hangs, and sweep.py's
    // subprocess timeout (320s) stays a strict upper bound.
    const proxyTimeoutMs = parseInt(process.env.BRIDGE_TIMEOUT_MS || '300000', 10);
    const watchdogMs = proxyTimeoutMs + 10000;
    const timer = setTimeout(() => { ws.close(); reject(new Error('timeout')); }, watchdogMs);
    ws.on('open', () => {
      ws.send(JSON.stringify({ type: 'PROXY_EXECUTE', id, code: wrapped, timeout: proxyTimeoutMs }));
    });
    ws.on('message', (data) => {
      const msg = JSON.parse(data.toString());
      if (msg.type === 'PROXY_EXECUTE_RESULT' && msg.id === id) {
        clearTimeout(timer);
        ws.close();
        if (msg.error) reject(new Error(msg.error));
        else {
          // Phase E #5 fix (2026-04-26): surface bridge-side failures
          // verbatim. Pre-fix when the bridge reported
          // {success: false, error: "..."} the script tried to read
          // msg.result.result (undefined) and rejected with the opaque
          // "no result in {...}" envelope. Now we extract the real
          // error from the envelope so Python sees the actual cause
          // (e.g. plugin sandbox eval timeout, WebSocket closed,
          // proxy_execute timeout from Figma's side).
          // Codex 2026-04-26 (gpt-5.5 high reasoning): "low-risk,
          // directly improves the next failure, and does not change
          // timeout semantics or mask regressions."
          const envelope = msg.result || {};
          if (envelope.success === false || envelope.error) {
            reject(new Error(envelope.error || 'bridge execution failed'));
            return;
          }
          const result = envelope.result;
          if (!result) {
            reject(new Error('no result in ' + JSON.stringify(msg).slice(0, 500)));
            return;
          }
          fs.writeFileSync(outPath, JSON.stringify(result, null, 2));
          const err_ct = (result.errors || []).length;
          const eid_ct = Object.keys(result.eid_map || {}).length;
          const vec_missing = Object.values(result.eid_map || {}).filter(
            e => (e.type === 'VECTOR' || e.type === 'BOOLEAN_OPERATION')
              && e.fillGeometryCount === 0 && e.strokeGeometryCount === 0
          ).length;
          console.log(
            'wrote ' + outPath + ' — ' + eid_ct + ' eids, '
            + err_ct + ' errors, ' + vec_missing + ' missing vector assets'
          );
          resolve();
        }
      }
    });
    ws.on('error', (e) => { clearTimeout(timer); reject(e); });
  });
}

run().catch((e) => { console.error('FAIL:', e.message); process.exit(1); });
